# Generated by Django 2.2 on 2021-09-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
