# Generated by Django 2.2 on 2021-10-03 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211003_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='selectedAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserAddress'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
