# Generated by Django 2.2 on 2022-01-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
