# Generated by Django 2.2 on 2022-01-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sessionsoppingcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionSoppingCart',
            new_name='SessionShoppingCart',
        ),
    ]
