# Generated by Django 2.2 on 2022-01-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220115_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.PaymentMode'),
            preserve_default=False,
        ),
    ]
